DROP TABLE if exists Temperature;
CREATE TABLE Temperature (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  reading REAL NOT NULL
);

DROP TABLE if exists Humidity;
CREATE TABLE Humidity (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  reading REAL NOT NULL
);

DROP TABLE if exists Gate;
CREATE TABLE Gate (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  reading INTEGER NOT NULL
);

DROP TABLE if exists Audio;
CREATE TABLE Audio (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  reading INTEGER NOT NULL
);

DROP TABLE if exists Envelope;
CREATE TABLE Envelope (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  reading INTEGER NOT NULL
);

DROP TABLE if exists Light;
CREATE TABLE Light (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  reading INTEGER NOT NULL
);
